{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "043ffd10",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: mysql-connector-python in c:\\users\\niraj khatri\\anaconda jupyter\\lib\\site-packages (9.1.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install mysql-connector-python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3df4823e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pymysql\n",
    "import mysql.connector\n",
    "import os\n",
    "from sqlalchemy import create_engine"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b256b7f3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Niraj khatri\n"
     ]
    }
   ],
   "source": [
    "#Here We check the current working directory\n",
    "current_directory = os.getcwd()\n",
    "print(current_directory)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "cf080537",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Chnage the CWD to the path where our file is located\n",
    "path ='D:\\\\Data Analytics\\\\Pizza sales\\\\pizza_sales'\n",
    "change_directory = os.chdir(path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b4240a17",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Read CSV File and we have 4-CSV files\n",
    "Order_details = pd.read_csv('order_details.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b845a55b",
   "metadata": {},
   "outputs": [],
   "source": [
    "Orders = pd.read_csv('orders.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "bfaeadfb",
   "metadata": {},
   "outputs": [],
   "source": [
    "pizzas = pd.read_csv('pizzas.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "52300c8c-a8fd-4d2e-ae7e-088b8973aaf7",
   "metadata": {},
   "outputs": [],
   "source": [
    "pizza_types=pd.read_csv(\"pizza_types.csv\",encoding='latin1')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "3df95c2f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Establish a connection between your Python application and the MySQL database\n",
    "engine = create_engine('mysql+mysqlconnector://root:root@localhost:3306/pizza_sales')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "709f441b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Niraj khatri\\AppData\\Local\\Temp\\ipykernel_9604\\1188333865.py:2: UserWarning: The provided table name 'Order_details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  Order_details.to_sql('Order_details',con=engine,if_exists='append',index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "48620"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Write DataFrame to MySQL Table\n",
    "Order_details.to_sql('Order_details',con=engine,if_exists='append',index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "01bf6c2d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Niraj khatri\\AppData\\Local\\Temp\\ipykernel_9604\\3064846717.py:1: UserWarning: The provided table name 'Orders' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  Orders.to_sql('Orders',con=engine,if_exists='append',index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "21350"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "Orders.to_sql('Orders',con=engine,if_exists='append',index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "d1b0fdee",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "96"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pizzas.to_sql('pizzas',con=engine,if_exists='append',index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "783f2e29",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Niraj khatri\\AppData\\Local\\Temp\\ipykernel_9604\\1777503616.py:1: UserWarning: The provided table name 'Pizza_types' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  pizza_types.to_sql('Pizza_types',con=engine,if_exists='append',index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "32"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pizza_types.to_sql('Pizza_types',con=engine,if_exists='append',index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
